### ISSUE TITLE
Unable to start Peer

### ISSUE THREAD

**Issue by chickenduy** [textileio/android-ipfs-lite#8]
After calling the static function start() in litePeer, exception is thrown:
`Map log file. Path=/data/user/0/<package>/files/ipfslite/000000.vlog. Error=cannot allocate memory`

**Comment by carsonfarmer** [comment]
I think this latest fix from @andrewxhill should address this: #14

**Comment by andrewxhill** [comment]
Yes, exactly. Please be sure to wipe your simulator. Then start your peer with the lowmem option set to true, see here:

https://github.com/textileio/android-ipfs-lite/pull/14/files#diff-04c6e90faac2675aa89e2176d2eec7d8R95
